name: Build app

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      # See https://github.com/npm/cli/issues/4828
      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build app
        run: npm run build
