name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    uses: "./.github/workflows/build.yaml"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
